## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('wifi-test', ['core', 'internet', 'point-to-point', 'point-to-point-layout', 'traffic-control', 'applications','mobility','wifi'])
    obj.source = 'wifi-test.cc'
